/* Data situs CELESTE (fiktif) — toko teleskop & observatorium wisata. */
export default {
 id:'celeste',type:'shop',frames:7,
 fonts:'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;700&family=Outfit:wght@400;500;600&display=swap',
 theme:{mode:'dark',bg:'#070916',bg2:'#0c1024',ink:'#ecebff',mut:'#9a98c0',acc:'#b9a6ff',accInk:'#140a33',line:'#1f2347',card:'#0f1330',fh:"'Cormorant Garamond',Georgia,serif",fb:"'Outfit',system-ui,sans-serif",radius:'10px'},
 brand:{name:'CELESTE',mark:'C',tagline:'Teleskop dan perlengkapan astronomi, plus malam pengamatan di observatorium kami.',email:'langit@celeste.example',phone:'(0274) 555-0166',address:'Jl. Kaliurang Km 21, Sleman, Yogyakarta'},
 promo:'Malam pengamatan setiap Sabtu · Kolimasi teleskop gratis seumur hidup',
 home:{eyebrow:'Toko teleskop & observatorium',title:'Lihat cincin <em>Saturnus</em> dengan mata sendiri.',sub:'Teleskop yang kami uji langsung di bawah langit lereng gunung, dengan panduan pemula dan dukungan kolimasi seumur hidup.',cta:'Pilih teleskop',heroImg:0,storyImg:3,storyTag:'Observatorium',storyTitle:'Kubah kecil di bawah bulan besar.',story:'Setiap Sabtu kami membuka kubah untuk pengunjung. Masuklah ke observatorium 3D: buka celah kubah, arahkan teleskop ke Saturnus, Jupiter, Mars, dan nebula.'},
 usp:[['Diuji di langit','Setiap teleskop dicoba sebelum dikirim'],['Kolimasi gratis','Seumur hidup di observatorium kami'],['Garansi 2 tahun','Optik dan mekanik'],['Panduan pemula','Kelas daring 30 menit gratis']],
 categories:[{id:'teleskop',name:'Teleskop',desc:'Refraktor & reflektor',img:3,pos:'50% 50%'},{id:'aksesori',name:'Aksesori',desc:'Lensa mata, filter, tripod',img:5,pos:'50% 50%'},{id:'wisata',name:'Malam Pengamatan',desc:'Tiket observatorium',img:2,pos:'50% 40%'}],
 products:[
  {id:'refraktor-cx80',cat:'teleskop',name:'Refraktor CX-80',short:'Refraktor 80 mm f/7, tajam untuk bulan dan planet.',price:7900000,badge:'Pilihan pemula',feat:1,img:3,pos:'50% 50%',rating:4.8,reviews:76,kw:['refraktor','cx-80','cx80'],variants:[{key:'Dudukan',label:'Dudukan',values:[{v:'Altaz manual'},{v:'Altaz + tracking',delta:3200000}]},{key:'Warna',label:'Tabung',values:[{v:'Putih',sw:'#efefef'},{v:'Biru malam',sw:'#1a2a5a'}]}],desc:'Lensa dua elemen dengan pelapis multi-coating, pencari red dot, dan dua lensa mata. Ringan dan cepat dipasang.',spec:[['Apertur','80 mm'],['Panjang fokus','560 mm (f/7)'],['Perbesaran maks.','160×'],['Berat','4,2 kg']]},
  {id:'dobson-8',cat:'teleskop',name:'Reflektor Dobson 8"',short:'Apertur besar, pandangan dalam ke nebula dan galaksi.',price:11500000,feat:1,img:4,pos:'50% 50%',rating:4.9,reviews:58,kw:['dobson','reflektor'],desc:'Dobson klasik dengan cermin parabola 203 mm. Dudukan kayu laminasi mudah diputar, dan tabung dapat dilepas untuk dibawa dengan mobil.',spec:[['Apertur','203 mm'],['Panjang fokus','1.200 mm (f/5,9)'],['Berat','14 kg'],['Perakitan','±20 menit']]},
  {id:'lensa-mata',cat:'aksesori',name:'Set Lensa Mata Plössl',short:'Empat lensa mata 6,3 / 10 / 15 / 25 mm.',price:1450000,feat:1,img:5,pos:'50% 50%',rating:4.7,reviews:92,kw:['lensa'],desc:'Lensa dengan lapang pandang lebar dan pelapis penuh, dalam kotak pelindung.',spec:[['Barrel','1,25 inci'],['Isi','4 lensa']]},
  {id:'filter-bulan',cat:'aksesori',name:'Filter Bulan & Planet',short:'Kurangi silau bulan, tingkatkan kontras planet.',price:390000,img:2,pos:'60% 50%',rating:4.6,reviews:44,kw:['filter'],desc:'Paket filter polarisasi variabel dan filter warna untuk Jupiter dan Mars.',spec:[['Ukuran','1,25 inci']]},
  {id:'peta-bintang',cat:'aksesori',name:'Peta Bintang Putar Nusantara',short:'Peta planisfer tahan air untuk lintang Indonesia.',price:129000,img:1,pos:'50% 50%',rating:4.8,reviews:150,kw:['peta'],desc:'Menunjukkan rasi bintang yang tampak dari lintang 6° LS–8° LU tiap bulan.',spec:[['Ukuran','30 cm'],['Bahan','PVC tahan air']]},
  {id:'tiket-pengamatan',cat:'wisata',name:'Tiket Malam Pengamatan',short:'Dua jam di observatorium dengan pemandu astronomi.',price:150000,badge:'Sabtu malam',img:0,pos:'50% 50%',rating:4.9,reviews:312,kw:['tiket'],variants:[{key:'Sesi',label:'Sesi',values:[{v:'19.00'},{v:'21.00'}]}],desc:'Mengamati bulan, planet, dan objek langit dalam dengan beberapa teleskop. Termasuk minuman hangat.',spec:[['Durasi','2 jam'],['Kapasitas','20 orang/sesi'],['Cuaca','Jadwal ulang gratis bila berawan']]}],
 coupons:{BINTANG10:{type:'percent',value:10,max:800000},LANGIT100:{type:'fixed',value:100000,min:1500000}},freeShip:2000000,
 shipping:[{id:'reg',name:'Reguler berasuransi',eta:'2–4 hari kerja',price:45000},{id:'exp',name:'Ekspres',eta:'1–2 hari',price:95000}],
 payments:[{id:'va',name:'Virtual account bank',note:'BCA, Mandiri, BNI, BRI'},{id:'ewallet',name:'E-wallet / QRIS',note:'GoPay, OVO, DANA'},{id:'card',name:'Kartu kredit',note:'Cicilan 0% hingga 12 bulan'}],
 shipNote:'Teleskop dikirim dalam kardus ganda berasuransi. Kembalikan dalam 14 hari bila belum dipakai. Tiket observatorium dapat dijadwal ulang bila cuaca berawan.',
 testi:[['Pertama kali melihat cincin Saturnus. Anak saya terpukau.','Hendra S.','Yogyakarta'],['Dobson 8" ini luar biasa, nebula Orion terlihat jelas.','Ayu L.','Solo'],['Tim-nya sabar mengajari kolimasi.','Bayu M.','Semarang']],
 about:{title:'Cerita CELESTE',sub:'Observatorium keluarga yang membuka kubahnya untuk umum.',img:3,paras:['CELESTE berawal dari observatorium kecil milik seorang guru fisika di lereng Merapi. Banyak tetangga ingin ikut mengintip bulan.','Kini kami menjual teleskop yang kami uji sendiri, mengadakan malam pengamatan, dan melayani kolimasi seumur hidup.','Langit adalah milik semua. Kami ingin lebih banyak orang mengalaminya dengan mata sendiri.'],values:[['Uji langsung','Teleskop dicoba di langit sebelum dijual.'],['Ajarkan','Setiap pembelian disertai kelas pengantar.'],['Langit gelap','Kami mendukung pelestarian langit malam.']]},
 faq:[['Teleskop mana untuk pemula?','Refraktor CX-80 untuk kemudahan, Dobson 8" bila ingin melihat objek langit dalam.'],['Apakah perlu kolimasi?','Reflektor perlu kolimasi berkala; kami bantu gratis di observatorium.'],['Bagaimana bila malam berawan?','Tiket dapat dijadwal ulang tanpa biaya.'],['Apakah ada garansi?','2 tahun untuk optik dan mekanik.']],
 contact:{img:2,topics:['Pilih teleskop','Pesanan saya','Kunjungan observatorium','Lainnya'],hours:'Rabu–Minggu, 14.00–22.00 WIB'}
};
