/* Data situs FLORA (fiktif) — toko tanaman hias. */
export default {
 id:'flora',type:'shop',frames:7,
 fonts:'https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,700&family=Nunito+Sans:wght@400;600;700&family=Caveat:wght@600;700&display=swap',
 theme:{mode:'light',bg:'#f6f3ea',bg2:'#ece8da',ink:'#1d2a1c',mut:'#5d6c58',acc:'#3f8f2f',accInk:'#ffffff',line:'#d8d3bf',card:'#fffdf6',fh:"'Fraunces',Georgia,serif",fb:"'Nunito Sans',system-ui,sans-serif",radius:'14px'},
 brand:{name:'FLORA',mark:'F',tagline:'Tanaman hias sehat dari rumah kaca kami, dikirim dengan aman sampai pot di rumah Anda.',email:'halo@flora.example',phone:'(022) 555-0123',address:'Jl. Kebun Raya 7, Lembang, Bandung Barat'},
 promo:'Garansi tanaman hidup 14 hari · Gratis ongkir di atas Rp 500 ribu',
 home:{eyebrow:'Rumah kaca botani',title:'Hijaukan ruang, <em>pelan-pelan</em>.',sub:'Tanaman hias yang dirawat di rumah kaca berkabut Lembang, dilengkapi panduan rawat sehingga cocok untuk pemula.',cta:'Lihat tanaman',heroImg:3,storyImg:5,storyTag:'Dari rumah kaca kami',storyTitle:'Tiap tanaman diaklimatisasi 3 minggu.',story:'Tanaman tidak langsung dikirim. Kami membiasakannya dengan cahaya dalam ruangan agar tidak stres di rumah Anda. Masuklah ke rumah kaca kami dalam 3D, siram tanaman, lalu nyalakan lampu tumbuh.'},
 usp:[['Garansi 14 hari','Ganti bila tanaman layu saat tiba'],['Packing aman','Pot dilapis, daun dibungkus'],['Panduan rawat','Kartu & video untuk tiap tanaman'],['Tanaman aklimatisasi','Siap untuk cahaya dalam ruangan']],
 categories:[{id:'daun',name:'Tanaman Daun',desc:'Monstera, Ficus, Calathea',img:1,pos:'50% 50%'},{id:'pot',name:'Pot & Media',desc:'Terakota, keramik, tanah racik',img:4,pos:'60% 60%'},{id:'alat',name:'Perawatan',desc:'Lampu tumbuh, pupuk, penyiram',img:5,pos:'50% 40%'}],
 products:[
  {id:'monstera',cat:'daun',name:'Monstera Deliciosa',short:'Daun belah ikonik, tumbuh cepat di cahaya terang tidak langsung.',price:289000,badge:'Terlaris',feat:1,img:1,pos:'45% 50%',rating:4.9,reviews:214,kw:['monstera'],variants:[{key:'Ukuran',label:'Ukuran pot',values:[{v:'Pot 20 cm'},{v:'Pot 25 cm',delta:150000},{v:'Pot 30 cm',delta:320000}]},{key:'Pot',label:'Pot',values:[{v:'Terakota',sw:'#b8613a'},{v:'Putih',sw:'#f2f2ee',hue:0},{v:'Abu',sw:'#777'}]}],desc:'Monstera dewasa muda dengan 6–9 daun berlubang. Cocok untuk pemula: toleran terhadap lupa menyiram.',spec:[['Cahaya','Terang tidak langsung'],['Siram','Saat 3 cm tanah atas kering'],['Tinggi','60–80 cm'],['Aman hewan','Tidak']]},
  {id:'ficus-lyrata',cat:'daun',name:'Ficus Lyrata',short:'Daun lebar bentuk biola, pernyataan hijau untuk sudut ruang.',price:425000,feat:1,img:2,pos:'60% 40%',rating:4.7,reviews:156,kw:['ficus','lyrata'],variants:[{key:'Tinggi',label:'Tinggi',values:[{v:'80 cm'},{v:'110 cm',delta:380000},{v:'140 cm',delta:850000}]}],desc:'Menyukai cahaya jendela dan tidak suka dipindah-pindah. Kami kirim dengan penopang batang.',spec:[['Cahaya','Terang'],['Siram','Seminggu sekali'],['Tinggi','80–140 cm']]},
  {id:'calathea',cat:'daun',name:'Calathea Orbifolia',short:'Daun bergaris perak yang bergerak mengikuti cahaya.',price:195000,feat:1,img:4,pos:'50% 50%',rating:4.6,reviews:88,kw:['calathea'],desc:'Menyukai kelembapan tinggi. Gunakan air tanpa kaporit bila memungkinkan.',spec:[['Cahaya','Sedang'],['Siram','Jaga lembap'],['Aman hewan','Ya']]},
  {id:'pothos',cat:'daun',name:'Pothos Golden Gantung',short:'Menjuntai cantik, hampir mustahil mati.',price:89000,img:5,pos:'30% 60%',rating:4.8,reviews:320,kw:['pothos'],desc:'Pilihan terbaik untuk pemula dan ruang kurang cahaya. Bisa diperbanyak dari stek.',spec:[['Cahaya','Rendah–sedang'],['Panjang sulur','50–70 cm']]},
  {id:'pot-terakota',cat:'pot',name:'Pot Terakota Handmade',short:'Tanah liat pilihan, lubang drainase, tatakan serasi.',price:129000,img:3,pos:'70% 70%',rating:4.7,reviews:97,kw:['pot'],variants:[{key:'Ukuran',label:'Diameter',values:[{v:'20 cm'},{v:'25 cm',delta:40000},{v:'30 cm',delta:90000}]}],desc:'Pori-pori alami membantu akar bernapas dan mengurangi risiko busuk akar.',spec:[['Bahan','Terakota bakar tinggi'],['Drainase','Ya, dengan tatakan']]},
  {id:'media-racik',cat:'pot',name:'Media Tanam Racik Aroid',short:'Campuran arang sekam, kokedama, dan perlit, 5 liter.',price:75000,img:0,pos:'60% 80%',rating:4.8,reviews:140,kw:['media'],desc:'Racikan tinggi aerasi untuk aroid seperti monstera dan philodendron.',spec:[['Isi','5 liter'],['Komposisi','Arang sekam, kokedama, perlit, kompos']]},
  {id:'lampu-tumbuh',cat:'alat',name:'Lampu Tumbuh Magenta',short:'Spektrum penuh bergaya magenta untuk tanaman dalam ruangan.',price:349000,img:6,pos:'50% 40%',rating:4.6,reviews:63,kw:['lampu','grow'],desc:'LED hemat daya dengan timer otomatis 12 jam. Jepitan fleksibel untuk rak atau meja.',spec:[['Daya','24 W'],['Timer','4/8/12 jam'],['Panjang kabel','2 m']]}],
 coupons:{HIJAU10:{type:'percent',value:10,max:150000},ONGKIR25:{type:'fixed',value:25000,min:250000}},freeShip:500000,
 shipping:[{id:'reg',name:'Reguler',eta:'2–3 hari kerja',price:22000},{id:'exp',name:'Ekspres tanaman',eta:'1 hari kerja',price:48000}],
 payments:[{id:'va',name:'Virtual account bank',note:'BCA, Mandiri, BNI, BRI'},{id:'ewallet',name:'E-wallet / QRIS',note:'GoPay, OVO, DANA'},{id:'card',name:'Kartu kredit',note:'Cicilan 0%'},{id:'cod',name:'Bayar di tempat',note:'Area Bandung Raya'}],
 shipNote:'Tanaman dikirim Senin–Rabu. Foto tanaman saat tiba dalam 24 jam untuk klaim garansi 14 hari. Pot dan alat dapat dikembalikan 7 hari bila belum dipakai.',
 testi:[['Monstera-nya tiba segar dan tidak ada daun patah. Kartu perawatannya sangat membantu.','Nadia R.','Bandung'],['Packing-nya aman sekali, tanah tidak tumpah sedikit pun.','Fajar T.','Jakarta'],['Pothos saya tumbuh cepat. Harganya jujur.','Wulan S.','Semarang']],
 about:{title:'Cerita FLORA',sub:'Sebuah rumah kaca kecil di Lembang yang tumbuh karena para pelanggannya.',img:5,paras:['FLORA bermula dari hobi merawat tanaman di kaca belakang rumah pada 2018. Teman-teman minta dibawakan satu-dua pot, lalu menjadi toko.','Hingga kini kami memperbanyak sendiri sebagian besar tanaman dan mengaklimatisasi tiga minggu sebelum dikirim.','Kami percaya merawat tanaman adalah kebiasaan kecil yang menenangkan. Karena itu tiap pesanan menyertakan kartu perawatan dan jalur chat langsung ke tim kebun.'],values:[['Tumbuh pelan','Tanaman sehat butuh waktu, bukan dipaksa.'],['Jujur','Foto produk adalah foto tanaman yang akan Anda terima.'],['Ramah bumi','Kemasan daur ulang dan media tanpa gambut.']]},
 faq:[['Tanaman saya layu saat tiba, bagaimana?','Kirim foto dalam 24 jam; kami ganti atau kembalikan dana dalam garansi 14 hari.'],['Apakah cocok untuk ruangan kurang cahaya?','Pothos dan sansevieria cocok. Lampu tumbuh kami dapat membantu tanaman lain.'],['Berapa lama pengiriman?','Reguler 2–3 hari, ekspres 1 hari kerja ke kota besar di Jawa.'],['Apakah ada kartu perawatan?','Ya, tiap tanaman disertai kartu dan tautan video.']],
 contact:{img:1,topics:['Tanya perawatan','Pesanan saya','Kunjungan kebun','Lainnya'],hours:'Setiap hari, 08.00–17.00 WIB'}
};
