/* Data situs HELIX (fiktif) — klinik genomik. */
export default {
 id:'genom',type:'compro',frames:7,
 fonts:'https://fonts.googleapis.com/css2?family=Manrope:wght@500;700;800&family=Source+Sans+3:wght@400;500;600&display=swap',
 theme:{mode:'dark',bg:'#04101a',bg2:'#071a28',ink:'#e6f4fb',mut:'#86a7ba',acc:'#5fe6ff',accInk:'#021822',line:'#12344a',card:'#08202f',fh:"'Manrope',system-ui,sans-serif",fb:"'Source Sans 3',system-ui,sans-serif",radius:'10px'},
 brand:{name:'HELIX',mark:'H',tagline:'Klinik genomik dan laboratorium sekuensing yang menerjemahkan DNA menjadi keputusan kesehatan.',email:'layanan@helix.example',phone:'(021) 555-0133',address:'Gedung Helix, Jl. Kuningan Barat 9, Jakarta'},
 svcTitle:'Layanan',svcSub:'Dari tes skrining hingga sekuensing genom utuh, dengan konseling genetik.',projTitle:'Studi & kemitraan',projSub:'Penelitian dan layanan klinis bersama mitra rumah sakit.',projLabel:'Studi',
 home:{eyebrow:'Klinik & laboratorium genomik',title:'Semua cerita dimulai dari <em>satu sel</em>.',sub:'Kami membaca DNA Anda dengan akurasi tinggi dan menjelaskannya dalam bahasa manusia, bersama konselor genetik bersertifikat.',cta:'Lihat layanan',heroImg:0,
  stats:[['30','x','kedalaman sekuensing'],['99.9','%','akurasi varian'],['18','','rumah sakit mitra'],['14','hari','waktu hasil']],
  intro:{img:2,tag:'Tentang HELIX',title:'Sains yang dijelaskan dengan jelas.',text:'Hasil genetik sering membingungkan. Karena itu setiap laporan kami disertai sesi konseling. Jelajahi dunia sel di pengalaman 3D kami: urai heliks, pindai gen, dan lihat bagaimana setiap layanan bekerja.'},
  clients:['RS Pelita Medika','Institut Biosains Nusantara','Klinik Anugerah','Universitas Garuda','Asuransi Sentosa'],
  testi:[['Konselor menjelaskan hasil dengan sabar, tidak menakut-nakuti.','dr. Sinta M.','Mitra klinis (fiktif)'],['Laporan yang jelas dan bisa langsung dibawa ke dokter.','Budi H.','Pasien (fiktif)'],['Waktu hasil 14 hari memudahkan keputusan terapi kami.','Prof. Wirawan','Peneliti (fiktif)']]},
 services:[
  {id:'skrining-kanker',name:'Skrining Risiko Kanker Herediter',short:'Panel 84 gen untuk risiko kanker payudara, ovarium, kolorektal, dan lainnya.',img:2,desc:'Tes berbasis sampel ludah atau darah untuk mengetahui varian yang menaikkan risiko kanker herediter, disertai rencana pemantauan bersama dokter.',points:['Panel 84 gen terkurasi','Laporan dalam bahasa Indonesia','Konseling genetik pra dan pasca tes','Pelaporan varian yang dapat ditindaklanjuti'],steps:[['Konsultasi','Riwayat keluarga dan tujuan tes.'],['Sampel','Kit di rumah atau kunjungan klinik.'],['Analisis','Sekuensing dan interpretasi.'],['Konseling','Pembahasan hasil dan rencana.']]},
  {id:'farmakogenomik',name:'Farmakogenomik',short:'Cocokkan obat dan dosis dengan profil genetik Anda.',img:4,desc:'Menunjukkan bagaimana tubuh Anda memetabolisme obat tertentu sehingga dokter bisa memilih dosis dan jenis yang paling sesuai.',points:['Lebih dari 120 obat','Laporan untuk dokter dan pasien','Pembaruan seumur hidup','Terintegrasi rekam medis mitra'],steps:[['Pilih panel','Berdasarkan terapi yang sedang berjalan.'],['Sampel','Usap pipi.'],['Analisis','Varian metabolisme obat.'],['Laporan','Ke dokter pengampu.']]},
  {id:'genom-utuh',name:'Sekuensing Genom Utuh',short:'Peta lengkap 3 miliar pasangan basa dengan kedalaman 30×.',img:1,desc:'Untuk kasus penyakit langka dan penelitian. Analisis dilakukan ulang secara berkala saat basis pengetahuan berkembang.',points:['Kedalaman 30×','Analisis trio (anak+orang tua)','Reanalisis tahunan','Penyimpanan data terenkripsi'],steps:[['Evaluasi klinis','Indikasi dan persetujuan.'],['Sekuensing','Di laboratorium kami.'],['Interpretasi','Tim bioinformatika dan dokter.'],['Reanalisis','Tiap tahun tanpa biaya tambahan.']]},
  {id:'konseling',name:'Konseling Genetik',short:'Sesi 45 menit dengan konselor bersertifikat.',img:3,desc:'Memahami arti hasil, implikasi untuk keluarga, dan keputusan berikutnya — tanpa tekanan.',points:['Daring atau tatap muka','Rencana tindak lanjut tertulis','Dukungan keluarga','Rahasia medis terjaga'],steps:[['Jadwal','Pilih waktu yang sesuai.'],['Sesi','Diskusi hasil dan pertanyaan.'],['Ringkasan','Dokumen tertulis.'],['Tindak lanjut','Rujukan bila perlu.']]}],
 projects:[
  {id:'studi-kanker-payudara',name:'Skrining kanker payudara herediter di 6 rumah sakit',client:'Jaringan RS Pelita (fiktif)',sector:'Onkologi',year:2025,img:3,pos:'50% 50%',summary:'Program skrining untuk 4.200 pasien dengan riwayat keluarga.',challenge:'Banyak pasien terlambat mengetahui risiko herediter.',solution:'Alur rujukan terpadu dari dokter ke tes genetik dan konseling, dengan portal hasil yang aman.',results:[['4.200','pasien'],['6,1%','varian bermakna ditemukan'],['92%','mendapat konseling < 7 hari']]},
  {id:'farmako-jantung',name:'Farmakogenomik untuk antikoagulan',client:'Klinik Anugerah (fiktif)',sector:'Kardiologi',year:2025,img:4,pos:'50% 50%',summary:'Menyesuaikan dosis antikoagulan berdasarkan profil genetik.',challenge:'Dosis awal sering meleset sehingga memerlukan beberapa kunjungan.',solution:'Tes dilakukan sebelum terapi; dokter menerima rekomendasi dosis awal.',results:[['−35%','kunjungan penyesuaian dosis'],['2,1 hari','waktu hingga dosis stabil'],['380','pasien']]},
  {id:'penyakit-langka',name:'Diagnosis penyakit langka pada anak',client:'Institut Biosains Nusantara (fiktif)',sector:'Penyakit langka',year:2024,img:1,pos:'50% 50%',summary:'Sekuensing trio untuk mempersingkat odisei diagnostik.',challenge:'Keluarga menunggu rata-rata 5 tahun untuk diagnosis.',solution:'Sekuensing genom trio dengan analisis tim multidisiplin dan reanalisis berkala.',results:[['41%','mendapat diagnosis'],['8 minggu','waktu rata-rata'],['120','keluarga']]}],
 insights:[
  {id:'apa-itu-varian',title:'Apa arti “varian bermakna tidak pasti”?',date:'2026-08-05',tag:'Edukasi',img:2,excerpt:'Mengapa sebagian hasil tes genetik berkata “belum tahu” dan itu bukan kabar buruk.',body:['Varian bermakna tidak pasti (VUS) berarti ilmu pengetahuan belum cukup untuk menyimpulkan apakah varian itu berbahaya.','Sebagian besar VUS akhirnya diklasifikasi sebagai tidak berbahaya. Karena itu kami melakukan reanalisis berkala.','Jangan mengubah keputusan medis hanya karena VUS; diskusikan dengan konselor dan dokter.']},
  {id:'privasi-data',title:'Data genetik Anda: siapa yang boleh melihat?',date:'2026-06-18',tag:'Privasi',img:4,excerpt:'Bagaimana kami menyimpan dan membatasi akses data genomik.',body:['Data dienkripsi saat disimpan dan dikirim. Akses dicatat dan dibatasi pada personel yang memerlukan.','Data tidak dibagikan ke pihak ketiga, termasuk asuransi, tanpa persetujuan tertulis Anda.','Anda dapat meminta penghapusan sampel dan data kapan saja.']},
  {id:'siapa-yang-perlu',title:'Siapa yang sebaiknya mempertimbangkan tes genetik?',date:'2026-04-22',tag:'Panduan',img:3,excerpt:'Beberapa tanda riwayat keluarga yang perlu didiskusikan dengan dokter.',body:['Riwayat kanker pada usia muda, beberapa kerabat dengan kanker yang sama, atau penyakit langka dalam keluarga.','Konsultasikan dengan dokter atau konselor terlebih dahulu untuk menentukan tes yang tepat.','Tes bukan untuk semua orang; konseling membantu memutuskan.']}],
 about:{title:'Tentang HELIX',sub:'Dokter, ahli genetika, dan insinyur bioinformatika dengan satu misi: hasil yang bisa dipahami.',img:2,paras:['HELIX didirikan pada 2018 oleh tim klinisi dan peneliti yang melihat banyak pasien kebingungan membaca laporan genetik.','Laboratorium kami terakreditasi dan mengikuti pedoman internasional untuk interpretasi varian. Setiap laporan ditinjau oleh dokter spesialis genetika.'],values:[['Akurat','Validasi berlapis dan kontrol kualitas ketat.'],['Dijelaskan','Konseling bagian dari layanan.'],['Rahasia','Privasi dan persetujuan di atas segalanya.']],timeline:[[2018,'HELIX berdiri'],[2020,'Laboratorium terakreditasi'],[2022,'Panel farmakogenomik'],[2024,'Kemitraan 18 rumah sakit'],[2026,'Gedung baru dengan laboratorium terbuka']],team:[['dr. Anindya Prasetyo, Sp.GK','Direktur Medis'],['Dr. Farhan Hakim','Kepala Laboratorium'],['Larasati Putri, MSc','Kepala Bioinformatika'],['Sari Wulandari','Kepala Konseling']]},
 jobs:[{id:'bioinfo',title:'Bioinformatika',place:'Jakarta',type:'Penuh waktu',desc:'Membangun pipeline varian dan sistem pelaporan.',req:['Python/R, NGS','Pengalaman interpretasi varian','Teliti dan jelas']},{id:'konselor',title:'Konselor Genetik',place:'Jakarta / daring',type:'Penuh waktu',desc:'Mendampingi pasien memahami hasil tes.',req:['Sertifikasi konseling genetik','Empati dan komunikasi','Bahasa Inggris']}],
 faq:[['Apa yang diperlukan untuk tes?','Sampel ludah atau darah, formulir persetujuan, dan sesi konseling pra tes.'],['Berapa lama hasil keluar?','Skrining panel 14 hari kerja; genom utuh 6–8 minggu.'],['Apakah hasil dibagikan ke asuransi?','Tidak, tanpa persetujuan tertulis Anda.'],['Apakah tes ini diagnosis?','Skrining menunjukkan risiko; diagnosis ditegakkan dokter.']],
 contact:{img:2,topics:['Jadwalkan konseling','Kemitraan rumah sakit','Hasil tes saya','Media'],hours:'Senin–Jumat, 08.00–17.00 WIB',sub:'Kami menjawab pertanyaan tentang layanan dan prosedur. Untuk keadaan medis darurat, hubungi fasilitas kesehatan terdekat.'},
 cta:{title:'Ingin memahami risiko genetik Anda?',text:'Jadwalkan konsultasi awal dengan konselor kami, tanpa kewajiban tes.',btn:'Jadwalkan konsultasi'}
};
