/* Data situs KAZE 風 (fiktif) — butik sneaker edisi terbatas. */
export default {
 id:'kaze',type:'shop',frames:7,
 fonts:'https://fonts.googleapis.com/css2?family=Syne:wght@600;800&family=Manrope:wght@400;500;700&display=swap',
 theme:{mode:'dark',bg:'#0a0612',bg2:'#120a1f',ink:'#f4eefc',mut:'#a395bd',acc:'#ff2bd6',accInk:'#1a0016',line:'#2a1840',card:'#150c25',fh:"'Syne',system-ui,sans-serif",fb:"'Manrope',system-ui,sans-serif",radius:'6px'},
 brand:{name:'KAZE 風',mark:'風',tagline:'Sneaker edisi terbatas yang dirancang untuk kota basah dan malam panjang.',email:'cs@kaze.example',phone:'(021) 555-0188',address:'Gang Neon 3, Kemang, Jakarta Selatan'},
 promo:'Drop berikutnya Jumat 20.00 WIB · Ukur ulang gratis 30 hari',
 home:{eyebrow:'Edisi terbatas · Drop 02',title:'Berjalan di <em>kota basah</em>, bersinar di malamnya.',sub:'Sneaker dengan panel reflektif dan outsole anti-selip untuk jalanan hujan, diproduksi hanya 800 pasang per colorway.',cta:'Belanja drop',heroImg:3,storyImg:4,storyTag:'Desain',storyTitle:'Reflektif di mana lampu menyentuhnya.',story:'Setiap panel diuji di bawah lampu jalan dan hujan buatan. Datang ke butik 3D kami: ubah palet neon, ganti colorway, lalu putar sepatu 360 derajat.'},
 usp:[['Edisi terbatas','800 pasang per colorway'],['Ukur ulang gratis','Tukar ukuran 30 hari'],['Autentik','Kartu nomor seri tiap pasang'],['Kirim 1–2 hari','Jabodetabek via kurir instan']],
 categories:[{id:'sneaker',name:'Sneaker',desc:'Air Kaze & Neo Runner',img:3,pos:'50% 60%'},{id:'apparel',name:'Apparel',desc:'Jaket hujan reflektif',img:1,pos:'40% 50%'},{id:'aksesori',name:'Aksesori',desc:'Kaus kaki, tali, perawatan',img:4,pos:'50% 50%'}],
 products:[
  {id:'air-kaze-02',cat:'sneaker',name:'Air Kaze 02',short:'Siluet utama dengan panel reflektif dan midsole busa responsif.',price:1890000,badge:'Drop 02',feat:1,img:3,pos:'50% 60%',rating:4.9,reviews:188,kw:['air kaze','kaze'],variants:[{key:'Colorway',label:'Colorway',values:[{v:'Cyber',sw:'#2ad8ff'},{v:'Sunset',sw:'#ff7a3a',hue:140},{v:'Jade',sw:'#27d98b',hue:-60}]},{key:'Ukuran',label:'Ukuran EU',values:[{v:'40'},{v:'41'},{v:'42'},{v:'43'},{v:'44'}]}],desc:'Upper rajut dengan panel reflektif 3M, midsole busa dua kepadatan, dan outsole karet bertekstur khusus aspal basah.',spec:[['Upper','Rajut + panel reflektif'],['Midsole','Busa dua kepadatan'],['Outsole','Karet anti-selip'],['Berat','312 g (EU 42)']]},
  {id:'neo-runner',cat:'sneaker',name:'Neo Runner',short:'Sepatu lari kota ringan dengan sol bergerigi halus.',price:1650000,feat:1,img:2,pos:'50% 70%',rating:4.7,reviews:96,kw:['neo','runner'],variants:[{key:'Warna',label:'Warna',values:[{v:'Hitam',sw:'#111'},{v:'Putih',sw:'#eee'}]},{key:'Ukuran',label:'Ukuran EU',values:[{v:'40'},{v:'41'},{v:'42'},{v:'43'},{v:'44'}]}],desc:'Untuk lari malam di kota: bobot ringan, sol responsif, dan aksen reflektif di tumit.',spec:[['Berat','260 g'],['Drop','8 mm']]},
  {id:'jaket-hujan',cat:'apparel',name:'Jaket Hujan Reflektif',short:'Kedap air, ringan, lipat ke saku dada.',price:1290000,feat:1,img:1,pos:'40% 50%',rating:4.8,reviews:71,kw:['jaket'],variants:[{key:'Ukuran',label:'Ukuran',values:[{v:'S'},{v:'M'},{v:'L'},{v:'XL'}]}],desc:'Kain 3 lapis dengan jahitan lakban, kerah tinggi, dan garis reflektif di punggung.',spec:[['Bahan','Nylon 3 lapis'],['Tahan air','10.000 mm']]},
  {id:'kaus-kaki',cat:'aksesori',name:'Kaus Kaki Neon Crew',short:'Katun combed dengan benang reflektif, isi 3 pasang.',price:189000,img:4,pos:'50% 50%',rating:4.6,reviews:140,kw:['kaus'],desc:'Tumit dan ujung diperkuat, nyaman untuk seharian.',spec:[['Isi','3 pasang'],['Bahan','80% katun, 20% poliester']]},
  {id:'tali-reflektif',cat:'aksesori',name:'Tali Sepatu Reflektif',short:'Tali pipih dengan inti reflektif.',price:79000,img:5,pos:'60% 40%',rating:4.5,reviews:58,kw:['tali'],variants:[{key:'Panjang',label:'Panjang',values:[{v:'120 cm'},{v:'150 cm'}]}],desc:'Mudah dipasang pada semua sneaker KAZE dan sneaker lain.',spec:[['Bahan','Poliester + inti reflektif']]},
  {id:'kit-perawatan',cat:'aksesori',name:'Kit Perawatan Sneaker',short:'Pembersih, sikat, dan penyemprot pelindung air.',price:249000,img:0,pos:'50% 50%',rating:4.7,reviews:84,kw:['kit'],desc:'Menjaga panel reflektif dan upper rajut tetap bersih.',spec:[['Isi','Pembersih 100 ml, sikat, pelindung 150 ml']]}],
 coupons:{KAZE10:{type:'percent',value:10,max:250000},DROP50:{type:'fixed',value:50000,min:500000}},freeShip:1500000,
 shipping:[{id:'reg',name:'Reguler',eta:'2–3 hari kerja',price:25000},{id:'inst',name:'Kurir instan Jabodetabek',eta:'Hari ini',price:60000}],
 payments:[{id:'va',name:'Virtual account bank',note:'BCA, Mandiri, BNI, BRI'},{id:'ewallet',name:'E-wallet / QRIS',note:'GoPay, OVO, DANA'},{id:'card',name:'Kartu kredit',note:'Cicilan 0%'},{id:'cod',name:'Bayar di tempat',note:'Jabodetabek'}],
 shipNote:'Tukar ukuran gratis dalam 30 hari bila belum dipakai di luar ruangan dan kotak utuh. Pengembalian dana untuk produk cacat produksi.',
 testi:[['Panelnya benar-benar menyala saat kena lampu mobil. Nyaman dari hari pertama.','Kenji A.','Jakarta'],['Ukuran pas, kirim cepat, kotaknya keren.','Putri D.','Tangerang'],['Jaketnya ringan dan beneran anti air.','Bagas H.','Depok']],
 about:{title:'Cerita KAZE',sub:'Lahir dari gang sempit di Kemang yang tak pernah kering setelah jam sepuluh malam.',img:3,paras:['KAZE dirancang oleh tiga teman desainer yang bosan dengan sepatu yang licin di jalanan basah.','Produksi kami terbatas agar tiap drop tetap spesial dan agar kami bisa menjaga kualitas pengerjaan.','Dalam butik 3D kami, Anda bisa mencoba palet dan colorway sebelum memutuskan.'],values:[['Terbatas','Produksi kecil, kualitas terjaga.'],['Berguna','Reflektif untuk keselamatan, bukan hanya gaya.'],['Terbuka','Kami menulis bahan dan proses produksi.']]},
 faq:[['Bagaimana memilih ukuran?','Gunakan panduan ukur di halaman produk; tukar gratis dalam 30 hari.'],['Apakah produk original?','Ya, setiap pasang bernomor seri dan terdaftar.'],['Kapan drop berikutnya?','Pengumuman lewat email dan Instagram sepekan sebelumnya.'],['Apakah bisa preorder?','Ya, untuk ukuran yang habis dengan estimasi 3–4 minggu.']],
 contact:{img:1,topics:['Ukuran & fitting','Pesanan saya','Kolaborasi','Lainnya'],hours:'Setiap hari, 11.00–21.00 WIB'}
};
