/* Data situs KAWAH KOPI (fiktif) — roastery kopi vulkanik. */
export default {
 id:'kopi',type:'shop',frames:7,
 fonts:'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600;800&family=Karla:wght@400;500;700&display=swap',
 theme:{mode:'dark',bg:'#120c08',bg2:'#1a110b',ink:'#f5ebdf',mut:'#b19c88',acc:'#ff9a3a',accInk:'#2a1200',line:'#3a281b',card:'#1e140d',fh:"'Playfair Display',Georgia,serif",fb:"'Karla',system-ui,sans-serif",radius:'10px'},
 brand:{name:'KAWAH KOPI',mark:'K',tagline:'Kopi single origin dari lereng gunung api, disangrai segar setiap pekan.',email:'seduh@kawahkopi.example',phone:'(0361) 555-0155',address:'Jl. Lereng Kawah 5, Kintamani, Bali'},
 promo:'Disangrai Senin & Kamis, dikirim di hari yang sama · Langganan hemat 10%',
 home:{eyebrow:'Roastery vulkanik',title:'Kopi yang tumbuh di <em>tanah berapi</em>.',sub:'Biji arabika dari kebun terasering 1.400 mdpl, disangrai kecil-kecilan dan dikirim segar ke cangkir Anda.',cta:'Belanja kopi',heroImg:0,storyImg:4,storyTag:'Dari kebun ke sangrai',storyTitle:'Tanah vulkanik, rasa yang berlapis.',story:'Mineral tanah gunung api memberi karakter manis dan bersih. Masuk ke roastery 3D: ubah tingkat sangrai, lihat warna biji, dan seduh di meja seduh kami.'},
 usp:[['Disangrai segar','Tanggal sangrai di tiap kemasan'],['Langganan fleksibel','Jeda atau batalkan kapan saja'],['Petani sejahtera','Harga di atas pasar, transparan'],['Gratis ongkir','Di atas Rp 300 ribu']],
 categories:[{id:'biji',name:'Biji Kopi',desc:'Light, Medium, Dark',img:3,pos:'50% 50%'},{id:'alat',name:'Alat Seduh',desc:'V60, French press, gooseneck',img:5,pos:'50% 50%'},{id:'langganan',name:'Langganan',desc:'Kopi tiap dua minggu',img:2,pos:'50% 50%'}],
 products:[
  {id:'biji-kawah',cat:'biji',name:'Biji Kopi Kawah',short:'Arabika 1.400 mdpl, pilih tingkat sangrai sesuai selera.',price:95000,badge:'Terlaris',feat:1,img:3,pos:'50% 50%',rating:4.9,reviews:402,kw:['biji kopi','kawah'],variants:[{key:'Sangrai',label:'Tingkat sangrai',values:[{v:'Light',sw:'#b98c55'},{v:'Medium',sw:'#7c4b2b',hue:-8},{v:'Dark',sw:'#2e1a10',hue:-14}]},{key:'Berat',label:'Berat',values:[{v:'200 g'},{v:'500 g',delta:120000},{v:'1 kg',delta:300000}]},{key:'Giling',label:'Gilingan',values:[{v:'Biji utuh'},{v:'Espresso'},{v:'V60 / filter'},{v:'French press'}]}],desc:'Light: floral, jeruk, teh hitam. Medium: cokelat, karamel, kacang. Dark: pahit manis, asap, kakao. Disangrai saat dipesan.',spec:[['Varietas','Kintamani Arabika'],['Proses','Washed'],['Ketinggian','1.400 mdpl'],['Suhu sangrai','196–224 °C']]},
  {id:'blend-lava',cat:'biji',name:'Blend Lava Espresso',short:'Campuran medium-dark untuk espresso dan susu.',price:89000,feat:1,img:1,pos:'50% 50%',rating:4.8,reviews:178,kw:['blend','lava'],variants:[{key:'Berat',label:'Berat',values:[{v:'200 g'},{v:'500 g',delta:110000}]}],desc:'Body tebal, manis cokelat, nyaman dengan susu. Cocok untuk mesin espresso rumah.',spec:[['Komposisi','70% arabika, 30% robusta premium'],['Sangrai','Medium-dark']]},
  {id:'v60-set',cat:'alat',name:'Set Seduh V60 Keramik',short:'Dripper keramik, server kaca, dan 100 filter kertas.',price:349000,feat:1,img:5,pos:'50% 50%',rating:4.7,reviews:94,kw:['v60'],variants:[{key:'Warna',label:'Warna',values:[{v:'Hitam arang',sw:'#222'},{v:'Putih',sw:'#eee'},{v:'Terakota',sw:'#b8613a'}]}],desc:'Dripper berpori kecil untuk ekstraksi yang konsisten, dengan panduan resep dasar.',spec:[['Isi','Dripper, server 600 ml, 100 filter'],['Bahan','Keramik & kaca borosilikat']]},
  {id:'gooseneck',cat:'alat',name:'Ketel Gooseneck 0,9 L',short:'Aliran halus terkontrol, pegangan anti panas.',price:529000,img:4,pos:'50% 50%',rating:4.8,reviews:66,kw:['ketel','gooseneck'],desc:'Stainless steel dengan leher angsa presisi untuk tuang pelan.',spec:[['Kapasitas','0,9 L'],['Bahan','Stainless 304']]},
  {id:'langganan-bulanan',cat:'langganan',name:'Langganan Kopi Bulanan',short:'Dua kantong 200 g tiap dua minggu, pilihan barista.',price:178000,badge:'Hemat 10%',img:2,pos:'50% 50%',rating:4.9,reviews:131,kw:['langganan'],variants:[{key:'Frekuensi',label:'Pengiriman',values:[{v:'Tiap 2 minggu'},{v:'Tiap bulan'}]}],desc:'Kami memilih dua kopi terbaik pekan itu. Jeda atau batalkan kapan saja.',spec:[['Isi','2 × 200 g'],['Penagihan','Per pengiriman']]},
  {id:'gelas-seduh',cat:'alat',name:'Gelas Seduh Vulkanik 2 pcs',short:'Gelas keramik glasir kawah, isi 2.',price:219000,img:0,pos:'50% 50%',rating:4.6,reviews:49,kw:['gelas'],desc:'Dibuat tangan oleh pengrajin lokal dengan glasir bergradasi seperti lava.',spec:[['Kapasitas','240 ml'],['Isi','2 buah']]}],
 coupons:{KAWAH10:{type:'percent',value:10,max:100000},NGOPI25:{type:'fixed',value:25000,min:200000}},freeShip:300000,
 shipping:[{id:'reg',name:'Reguler',eta:'2–3 hari kerja',price:22000},{id:'exp',name:'Ekspres',eta:'1 hari kerja',price:45000}],
 payments:[{id:'va',name:'Virtual account bank',note:'BCA, Mandiri, BNI, BRI'},{id:'ewallet',name:'E-wallet / QRIS',note:'GoPay, OVO, DANA'},{id:'card',name:'Kartu kredit',note:'Cicilan 0%'},{id:'cod',name:'Bayar di tempat',note:'Kota tertentu'}],
 shipNote:'Disangrai Senin dan Kamis, dikirim di hari yang sama. Bila rasa tidak sesuai, hubungi kami dalam 7 hari untuk tukar atau kembalikan dana. Alat seduh: retur 14 hari.',
 testi:[['Light roast-nya wangi jeruk, bersih sekali.','Gita N.','Jakarta'],['Langganannya praktis, kopi selalu baru.','Anton R.','Denpasar'],['V60 set-nya cantik dan hasil seduhan konsisten.','Lia K.','Surabaya']],
 about:{title:'Cerita KAWAH KOPI',sub:'Dari kebun terasering di lereng gunung api ke cangkir Anda.',img:4,paras:['KAWAH KOPI dimulai oleh sebuah koperasi petani Kintamani yang ingin menyangrai sendiri hasil panennya.','Kami menyangrai kecil-kecilan tiap pekan, menuliskan tanggal sangrai di setiap kemasan, dan membayar petani di atas harga pasar.','Roastery kami terbuka untuk dikunjungi: Anda bisa melihat proses sangrai dan ikut sesi cupping.'],values:[['Segar','Disangrai sesuai pesanan.'],['Adil','Harga petani transparan.'],['Jujur','Catatan rasa apa adanya.']]},
 faq:[['Seberapa segar kopinya?','Disangrai Senin dan Kamis, dikirim di hari yang sama, tanggal tertera di kemasan.'],['Sangrai mana untuk saya?','Light untuk rasa buah dan teh, medium untuk seimbang, dark untuk pahit manis dan susu.'],['Bisakah digiling?','Ya, pilih gilingan saat memesan.'],['Bagaimana membatalkan langganan?','Kapan saja dari halaman kontak atau email konfirmasi.']],
 contact:{img:2,topics:['Pilih kopi','Pesanan saya','Kunjungan roastery','Lainnya'],hours:'Setiap hari, 08.00–18.00 WITA'}
};
