/* Data situs NEXUS·AI (fiktif). Dipakai oleh js/world/nexus.js (situs di dalam adegan 3D). */
export default {
 id:'nexus',type:'compro',frames:7,
 fonts:'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;700&family=Inter:wght@400;500;600&display=swap',
 theme:{mode:'dark',bg:'#050b14',bg2:'#09131f',ink:'#e8f1f8',mut:'#8ba3b8',acc:'#4fe0ff',accInk:'#021720',line:'#14283a',card:'#0b1826',fh:"'Space Grotesk',system-ui,sans-serif",fb:"Inter,system-ui,sans-serif",radius:'8px'},
 brand:{name:'NEXUS·AI',mark:'N',tagline:'Kecerdasan buatan yang bekerja di lantai produksi, bukan hanya di presentasi.',email:'hello@nexus-ai.example',phone:'(021) 555-0199',address:'Menara Nexus, Jl. Sudirman Kav. 88, Jakarta'},
 svcTitle:'Layanan',svcSub:'Dari data mentah sampai agen AI yang berjalan di operasional harian.',projTitle:'Proyek & studi kasus',projSub:'Beberapa pekerjaan terpilih bersama klien kami.',projLabel:'Proyek',
 home:{eyebrow:'Konsultan & rekayasa AI',title:'AI yang <em>benar-benar</em> dipakai tim Anda.',sub:'Kami merancang, membangun, dan mengoperasikan sistem AI untuk perusahaan — dengan tata kelola data yang bisa diaudit.',cta:'Lihat layanan',heroImg:0,
  stats:[['120','+','proyek produksi'],['14','','industri'],['99.95','%','uptime platform'],['9','','tahun berkarya']],
  intro:{img:2,tag:'Tentang kami',title:'Dari server room ke ruang rapat.',text:'Tim kami campuran insinyur ML, data, dan produk. Kami bekerja berdampingan dengan tim Anda sampai model yang dibangun benar-benar mengubah angka bisnis. Kunjungi kantor kami dalam 3D untuk melihat bagaimana ruang kerja dan server room kami bekerja.'},
  clients:['Arunika Bank','Tirta Logistik','Bumi Energi','Santika Retail','Meridian Health'],
  testi:[['Dalam enam bulan, waktu verifikasi dokumen turun dari dua hari menjadi dua jam.','Maya Pratiwi','COO, Arunika Bank (fiktif)'],['Mereka menjelaskan batas model dengan jujur. Itu yang membuat kami percaya.','Ardi Wibowo','CTO, Tirta Logistik (fiktif)'],['Platform datanya rapi dan bisa diaudit. Tim kepatuhan kami lega.','Lestari Dewi','Kepala Risiko, Bumi Energi (fiktif)']]},
 services:[
  {id:'platform-data',name:'Platform Data & MLOps',short:'Fondasi data, pipeline, dan operasional model yang andal.',img:2,desc:'Kami membangun lakehouse, katalog data, dan jalur MLOps sehingga model bisa dilatih ulang, diuji, dan diterapkan tanpa drama.',points:['Arsitektur lakehouse dan katalog data','Pipeline pelatihan & penerapan otomatis','Pemantauan drift dan kualitas model','Kontrol akses dan jejak audit'],steps:[['Audit','Memetakan sumber data, kualitas, dan risiko.'],['Rancang','Menentukan arsitektur dan jalur migrasi.'],['Bangun','Iterasi dua mingguan dengan demo.'],['Operasikan','Serah terima, pelatihan, dan dukungan.']]},
  {id:'agen-ai',name:'Agen AI untuk Operasional',short:'Asisten yang menjalankan alur kerja nyata dengan pengawasan manusia.',img:4,desc:'Agen kami terhubung ke sistem internal Anda, mengerjakan tugas berulang, dan meminta persetujuan manusia pada keputusan yang berisiko.',points:['Otomasi layanan pelanggan dan back-office','Integrasi ERP, CRM, dan tiket','Evaluasi berkelanjutan terhadap kasus uji','Batas wewenang dan persetujuan manusia'],steps:[['Temukan','Memilih alur kerja bernilai tinggi.'],['Prototipe','Agen terbatas di lingkungan uji.'],['Uji','Evaluasi dengan data nyata.'],['Luncurkan','Bertahap dengan pemantauan ketat.']]},
  {id:'vision-edge',name:'Vision & Edge AI',short:'Pengenalan visual di perangkat untuk pabrik, gudang, dan ritel.',img:5,desc:'Model visi yang berjalan di perangkat tepi dengan latensi rendah, cocok untuk inspeksi kualitas, keselamatan kerja, dan penghitungan stok.',points:['Inspeksi cacat dan keselamatan','Pemrosesan di perangkat tepi','Dasbor operasional waktu nyata','Privasi: data tidak keluar lokasi'],steps:[['Survei','Kunjungan lokasi dan pengumpulan data.'],['Latih','Model disesuaikan kondisi lapangan.'],['Pasang','Instalasi kamera dan perangkat.'],['Tingkatkan','Pembelajaran dari koreksi operator.']]},
  {id:'tata-kelola',name:'Penasihat & Tata Kelola AI',short:'Kebijakan, risiko, dan kepatuhan agar AI aman digunakan.',img:1,desc:'Kami membantu dewan dan tim hukum menyusun kerangka tata kelola AI yang praktis: inventaris model, penilaian risiko, dan kontrol yang dapat diaudit.',points:['Inventaris dan klasifikasi risiko model','Kebijakan penggunaan AI internal','Pelatihan eksekutif dan tim','Persiapan audit dan regulasi'],steps:[['Inventaris','Mendata penggunaan AI saat ini.'],['Nilai','Menilai risiko dan dampak.'],['Rancang','Kebijakan dan kontrol.'],['Latih','Sosialisasi ke seluruh tim.']]}],
 projects:[
  {id:'arunika-verifikasi',name:'Verifikasi dokumen otomatis',client:'Arunika Bank (fiktif)',sector:'Keuangan',year:2025,img:3,pos:'50% 50%',summary:'Mempercepat verifikasi dokumen pembiayaan tanpa mengurangi kendali manusia.',challenge:'Verifikasi manual memakan dua hari kerja dan rentan salah ketik. Volume permohonan naik 3× dalam dua tahun.',solution:'Agen ekstraksi dokumen dengan skor keyakinan; kasus ragu otomatis diarahkan ke verifikator, dan semua keputusan tercatat untuk audit.',results:[['−94%','waktu verifikasi'],['99,2%','akurasi ekstraksi'],['6 bln','hingga produksi']]},
  {id:'tirta-gudang',name:'Penghitungan stok berbasis visi',client:'Tirta Logistik (fiktif)',sector:'Logistik',year:2025,img:5,pos:'50% 50%',summary:'Kamera gudang menghitung palet dan mendeteksi selisih stok setiap jam.',challenge:'Stok opname bulanan menghentikan operasi dua hari dan tetap menyisakan selisih.',solution:'Model visi di perangkat tepi memantau rak dan menyocokkan dengan sistem gudang; selisih langsung dikirim ke supervisor.',results:[['−71%','selisih stok'],['0 hari','penghentian opname'],['12','gudang aktif']]},
  {id:'bumi-prediksi',name:'Prediksi perawatan turbin',client:'Bumi Energi (fiktif)',sector:'Energi',year:2024,img:2,pos:'50% 40%',summary:'Memprediksi kerusakan turbin dari data sensor sebelum terjadi.',challenge:'Kerusakan tak terduga menyebabkan penghentian produksi dan biaya darurat tinggi.',solution:'Model deret waktu pada data getaran dan suhu, dengan peringatan dini dan penjelasan faktor penyebab untuk teknisi.',results:[['−38%','henti tak terjadwal'],['21 hari','rata-rata peringatan dini'],['Rp 14 M','penghematan/tahun*']]}],
 insights:[
  {id:'agen-bukan-chatbot',title:'Agen AI bukan sekadar chatbot yang lebih pintar',date:'2026-08-12',tag:'Agen AI',img:4,excerpt:'Mengapa agen perlu batas wewenang, bukan hanya prompt yang bagus.',body:['Chatbot menjawab; agen bertindak. Perbedaan kecil itu mengubah cara kita merancang sistem: yang kita atur bukan lagi hanya apa yang boleh dikatakan, tetapi apa yang boleh dilakukan.','Pertama, tetapkan batas wewenang. Agen yang bisa membaca tiket tidak otomatis boleh menutupnya. Kedua, catat setiap tindakan dalam jejak audit yang bisa ditinjau manusia. Ketiga, ukur dengan kasus uji nyata, bukan demo.','Tim yang memulai dari alur kerja kecil dengan risiko rendah biasanya sampai ke produksi lebih cepat — dan membangun kepercayaan internal yang diperlukan untuk langkah berikutnya.']},
  {id:'data-dulu',title:'Sebelum model: tiga pertanyaan tentang data Anda',date:'2026-06-30',tag:'Data',img:2,excerpt:'Checklist ringkas sebelum memulai proyek AI.',body:['Banyak proyek AI gagal bukan karena modelnya, melainkan karena datanya. Sebelum memulai, jawab tiga pertanyaan berikut.','Siapa pemilik data ini, dan apakah penggunaannya diizinkan? Seberapa sering data diperbarui, dan siapa yang tahu bila formatnya berubah? Bagaimana kita tahu data hari ini masih seperti data saat model dilatih?','Jawaban yang jelas atas tiga pertanyaan itu menghemat berbulan-bulan pekerjaan ulang.']},
  {id:'tata-kelola-praktis',title:'Tata kelola AI yang praktis untuk perusahaan menengah',date:'2026-05-04',tag:'Tata kelola',img:1,excerpt:'Tidak perlu birokrasi tebal: mulai dari inventaris dan klasifikasi risiko.',body:['Tata kelola sering dibayangkan sebagai dokumen tebal. Dalam praktiknya, mulai dari daftar: apa saja sistem AI yang kita gunakan, siapa pemiliknya, dan data apa yang disentuh.','Dari daftar itu, kelompokkan berdasarkan risiko. Sistem berisiko rendah cukup dengan kontrol dasar; sistem berisiko tinggi memerlukan evaluasi, pemantauan, dan persetujuan manusia.','Tinjau setiap kuartal. Tata kelola yang hidup lebih berguna daripada yang sempurna di atas kertas.']}],
 about:{title:'Tentang NEXUS·AI',sub:'Insinyur, ilmuwan data, dan desainer produk yang percaya AI harus bisa dipertanggungjawabkan.',img:0,paras:['NEXUS·AI berdiri pada 2017 di Jakarta sebagai laboratorium kecil yang membantu perusahaan menerapkan pembelajaran mesin. Hari ini kami adalah tim 90 orang yang mengerjakan proyek di keuangan, logistik, energi, dan kesehatan.','Kami mengukur keberhasilan dengan satu pertanyaan: apakah tim klien masih memakainya setahun kemudian? Karena itu kami menekankan serah terima, dokumentasi, dan pelatihan sebagai bagian dari pekerjaan, bukan tambahan.'],
  values:[['Jujur soal batas','Kami menyampaikan apa yang tidak bisa dilakukan model.'],['Bisa diaudit','Setiap keputusan sistem bisa ditelusuri.'],['Manusia tetap memegang kendali','AI memperkuat, bukan menggantikan penilaian.']],
  timeline:[[2017,'Didirikan sebagai laboratorium ML'],[2019,'Platform MLOps pertama di produksi'],[2022,'Membuka praktik tata kelola AI'],[2024,'Meluncurkan layanan agen AI'],[2026,'Membuka kantor baru dengan server room terbuka']],
  team:[['Raka Mahendra','Pendiri & CEO'],['Dr. Nadia Kusuma','Kepala Riset'],['Bima Santoso','Kepala Rekayasa'],['Citra Anggraini','Kepala Tata Kelola']]},
 jobs:[{id:'ml-eng',title:'Machine Learning Engineer',place:'Jakarta / hibrida',type:'Penuh waktu',desc:'Membangun dan mengoperasikan model di produksi bersama tim klien.',req:['3+ tahun pengalaman ML di produksi','Python, PyTorch, dan praktik MLOps','Mampu menjelaskan trade-off ke non-teknis']},{id:'data-eng',title:'Data Engineer',place:'Jakarta / hibrida',type:'Penuh waktu',desc:'Merancang pipeline dan lakehouse yang andal dan terdokumentasi.',req:['SQL kuat, Spark atau sejenisnya','Pengalaman orkestrasi (Airflow, dbt)','Peduli kualitas dan observabilitas data']},{id:'pm',title:'Product Manager, Agen AI',place:'Jakarta',type:'Penuh waktu',desc:'Memimpin penemuan dan peluncuran agen AI untuk klien enterprise.',req:['Pengalaman produk B2B','Paham evaluasi sistem AI','Komunikasi tertulis yang jernih']}],
 faq:[['Berapa lama proyek AI pada umumnya?','Penemuan dan prototipe 4–8 minggu; menuju produksi umumnya 4–6 bulan, tergantung kesiapan data.'],['Apakah data kami keluar dari lingkungan kami?','Tidak perlu. Kami dapat bekerja di infrastruktur Anda dan mendukung penerapan on-premise.'],['Bagaimana model penagihannya?','Penemuan berbiaya tetap; pembangunan berbasis sprint; operasional berlangganan bulanan.'],['Apakah Anda menyediakan pelatihan?','Ya, untuk tim teknis dan eksekutif, termasuk modul tata kelola.']],
 contact:{img:2,topics:['Konsultasi proyek','Kemitraan','Media','Karier'],hours:'Senin–Jumat, 09.00–18.00 WIB',sub:'Ceritakan tantangan Anda. Tim kami membalas dalam satu hari kerja.'},
 cta:{title:'Punya tantangan yang ingin dipecahkan dengan AI?',text:'Jadwalkan sesi penemuan 45 menit tanpa biaya dengan tim kami.',btn:'Jadwalkan konsultasi'}
};
