/* Data situs SERENA (fiktif) — resor tropis. Template: js/site/compro.js */
export default {
 id:'serena',type:'compro',frames:9,
 fonts:'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;700&family=Jost:wght@400;500&display=swap',
 theme:{mode:'light',bg:'#fbf5ea',bg2:'#f2e8d6',ink:'#2a2118',mut:'#6b5d4c',acc:'#c8742a',accInk:'#ffffff',line:'#e0d2b8',card:'#fffaf0',fh:"'Cormorant Garamond',Georgia,serif",fb:"'Jost',system-ui,sans-serif",radius:'4px'},
 brand:{name:'SERENA',mark:'S',tagline:'Resor pulau kecil dengan dua puluh empat vila di atas laut yang tenang.',email:'reservasi@serena.example',phone:'(0361) 555-0177',address:'Pulau Serena, Kepulauan Karimun, Kepulauan Riau'},
 svcTitle:'Kamar & pengalaman',svcSub:'Dari vila di atas air hingga makan malam di dermaga.',projTitle:'Kamar & vila',projSub:'Pilih vila yang paling sesuai untuk liburan Anda.',projLabel:'Vila',
 home:{eyebrow:'Resor pulau · Kepulauan Riau',title:'Pulau kecil, <em>ketenangan</em> yang besar.',sub:'Dua puluh empat vila, satu teluk berair jernih, dan matahari terbenam yang tak perlu diburu.',cta:'Lihat kamar',heroImg:0,
  stats:[['24','','vila di atas air'],['4.8','/5','nilai tamu'],['12','','pemandu pulau'],['15','','tahun hospitality']],
  intro:{img:3,tag:'Tentang SERENA',title:'Dari udara, sebuah pulau. Dari dekat, sebuah rumah.',text:'Kami membangun SERENA dengan bahan lokal dan listrik surya. Lihat pulau dari ketinggian 90 meter di pengalaman 3D kami, turun ke garis pantai, lalu masuk ke vila dan pilih suasana siang atau malam.'},
  clients:['Condé Voyage','Bahari Tours','Archipelago Weddings','Selam Nusantara','Kopi Pulau'],
  testi:[['Bangun dengan suara ombak dan sarapan di dek. Tidak ada yang kurang.','Dian & Rangga','Bulan madu, Maret 2026 (fiktif)'],['Staf mengenal nama anak-anak saya pada hari kedua.','Maria L.','Liburan keluarga (fiktif)'],['Malam di dek, lampu kunang-kunang, laut diam. Sempurna.','Hadi W.','Perjalanan sendiri (fiktif)']]},
 services:[
  {id:'vila-air',name:'Vila di Atas Air',short:'Dek pribadi, tangga langsung ke laut, kolam rendam.',img:4,desc:'Vila 68 m² di atas laut dangkal dengan lantai kaca, dek pribadi, dan kolam rendam. Terdapat panel kaca besar yang terbuka ke laut.',points:['Tempat tidur king + sofa tidur','Dek pribadi dan tangga ke laut','Pendingin udara senyap','Sarapan di dek setiap pagi'],steps:[['Tiba','Penjemputan speedboat dari dermaga.'],['Beristirahat','Check-in di vila, bukan di meja resepsionis.'],['Menjelajah','Snorkeling, kayak, dan tur pulau.'],['Berpulang','Antar kembali ke dermaga dengan bekal.']]},
  {id:'vila-pantai',name:'Vila Pantai Keluarga',short:'Dua kamar tidur, taman kecil, langkah ke pasir.',img:5,desc:'Vila dua kamar dengan dapur kecil, taman, dan akses pantai pribadi. Ideal untuk keluarga atau kelompok kecil.',points:['Dua kamar tidur','Dapur kecil dan ruang makan','Pantai pribadi','Peralatan snorkeling anak'],steps:[['Pesan','Pilih tanggal dan susunan kamar.'],['Siapkan','Kami menyiapkan kebutuhan anak.'],['Tinggal','Layanan harian fleksibel.'],['Kenang','Foto keluarga di dermaga.']]},
  {id:'makan-malam',name:'Makan Malam di Dermaga',short:'Menu tujuh hidangan dengan hasil laut tangkapan hari itu.',img:2,desc:'Meja panjang di dermaga dengan lampu lentera. Menu berubah mengikuti tangkapan nelayan pulau.',points:['Menu 7 hidangan','Pendamping minuman opsional','Pilihan vegetarian','Maksimal 16 tamu per malam'],steps:[['Reservasi','Pilih malam saat check-in.'],['Aperitif','Matahari terbenam di ujung dermaga.'],['Makan','Hidangan bergulir pelan.'],['Penutup','Kopi pulau dan bintang.']]},
  {id:'spa',name:'Spa & Penyelaman',short:'Pijat rempah, yoga fajar, dan penyelaman bersama pemandu.',img:1,desc:'Rangkaian aktivitas yang menenangkan: yoga pukul 06.00, pijat rempah, dan penyelaman di terumbu karang yang dilindungi.',points:['Yoga fajar','Pijat rempah 60/90 menit','Penyelaman bersertifikat','Konservasi terumbu karang'],steps:[['Pilih','Susun jadwal bersama konsierge.'],['Persiapan','Peralatan disiapkan.'],['Nikmati','Bersama pemandu berpengalaman.'],['Pulih','Teh jahe di dek.']]}],
 projects:[
  {id:'vila-samudra',name:'Vila Samudra',client:'Di atas air · 2 tamu',sector:'Di atas air',year:2026,img:4,pos:'50% 50%',summary:'Vila 68 m² dengan lantai kaca dan dek menghadap barat.',challenge:'Banyak tamu ingin tinggal di atas air tetapi tetap merasa aman dan nyaman.',solution:'Vila berpondasi tiang baja anti karat, lantai kaca terpisah dari kamar tidur, dan akses tangga ke laut dengan pegangan.',results:[['68 m²','luas'],['2','tamu'],['Dari Rp 4,8 jt','per malam*']]},
  {id:'vila-karang',name:'Vila Karang',client:'Pantai · 4 tamu',sector:'Pantai',year:2026,img:5,pos:'50% 50%',summary:'Dua kamar tidur, taman, dan pantai pribadi.',challenge:'Keluarga membutuhkan ruang bersama dan privasi.',solution:'Dua kamar dipisah ruang tengah terbuka dengan dapur kecil dan taman berpagar.',results:[['2','kamar tidur'],['4','tamu'],['Dari Rp 6,2 jt','per malam*']]},
  {id:'vila-bintang',name:'Vila Bintang',client:'Di atas air · 2 tamu',sector:'Di atas air',year:2025,img:2,pos:'50% 50%',summary:'Vila dengan atap kaca untuk menatap bintang dari tempat tidur.',challenge:'Tamu ingin pengalaman malam yang tenang.',solution:'Atap kaca bertirai elektrik dan lampu redup hangat; mode malam mematikan lampu terang secara otomatis.',results:[['Atap kaca','buka-tutup'],['2','tamu'],['Dari Rp 5,5 jt','per malam*']]}],
 insights:[
  {id:'panduan-musim',title:'Kapan waktu terbaik berkunjung ke SERENA',date:'2026-07-20',tag:'Panduan',img:0,excerpt:'Musim laut tenang, matahari terbenam terbaik, dan kapan menghindari keramaian.',body:['Laut paling tenang pada Maret–Mei dan September–November. Visibilitas selam bisa mencapai 25 meter.','Matahari terbenam terbaik terlihat pada Mei–Agustus ketika langit lebih bersih.','Hindari akhir pekan panjang bila ingin dermaga hampir sendiri. Pesan lebih awal untuk tahun baru.']},
  {id:'terumbu',title:'Menjaga terumbu karang di halaman rumah kami',date:'2026-05-14',tag:'Konservasi',img:2,excerpt:'Program penanaman karang bersama nelayan pulau.',body:['Sejak 2022 kami menanam pecahan karang bersama nelayan setempat.','Tamu dapat ikut sesi penanaman dan memantau pertumbuhan lewat laporan triwulan.','Pendapatan sebagian sesi kembali ke koperasi nelayan.']},
  {id:'dapur-pulau',title:'Dapur pulau: dari tangkapan nelayan ke meja',date:'2026-03-02',tag:'Kuliner',img:5,excerpt:'Bagaimana menu makan malam berubah tiap hari.',body:['Chef kami memutuskan menu pukul 15.00, setelah perahu nelayan kembali.','Sayur dan rempah ditanam di kebun belakang vila staf.','Tidak ada menu yang sama dua malam berturut-turut.']}],
 about:{title:'Tentang SERENA',sub:'Resor kecil dengan komitmen besar pada pulau yang kami tinggali.',img:3,paras:['SERENA dibuka pada 2011 oleh keluarga yang tumbuh di Kepulauan Riau. Kami membangun dengan bahan lokal dan tenaga kerja dari pulau-pulau sekitar.','Listrik kami 70% dari surya, air minum dari penyulingan air laut, dan sampah dipilah di pulau. Kami menjaga jumlah tamu agar pulau tetap lengang.'],values:[['Lengang','24 vila saja, agar pulau tetap tenang.'],['Lokal','Staf, bahan, dan hidangan dari pulau sekitar.'],['Lestari','Surya, karang, dan nol plastik sekali pakai.']],timeline:[[2011,'SERENA dibuka dengan 8 vila'],[2016,'Vila di atas air pertama'],[2022,'Program penanaman karang'],[2025,'70% listrik dari surya'],[2026,'24 vila dan dermaga baru']],team:[['Ibu Ratna Surya','Pendiri'],['Pak Anwar','Kepala pulau'],['Chef Laras','Kepala dapur'],['Kak Dimas','Pemandu selam']]},
 jobs:[{id:'konsierge',title:'Konsierge Tamu',place:'Pulau Serena',type:'Kontrak 6 bulan',desc:'Mendampingi tamu sejak penjemputan hingga kepulangan.',req:['Komunikasi hangat','Bahasa Inggris aktif','Bersedia tinggal di pulau']},{id:'pemandu',title:'Pemandu Snorkeling',place:'Pulau Serena',type:'Penuh waktu',desc:'Memimpin tur dan menjaga keselamatan tamu di air.',req:['Sertifikat penyelam','Pertolongan pertama','Peduli konservasi']}],
 faq:[['Bagaimana menuju SERENA?','Terbang ke Batam, lalu speedboat 90 menit dari dermaga kami (jadwal 10.00 dan 15.00).'],['Apakah ada sinyal dan Wi-Fi?','Wi-Fi tersedia di area bersama; vila dibuat sengaja lebih senyap.'],['Apakah cocok untuk anak?','Vila Pantai dan program anak tersedia. Vila di atas air untuk usia 8+.'],['Bagaimana kebijakan pembatalan?','Gratis hingga 14 hari sebelum kedatangan.']],
 contact:{img:3,topics:['Reservasi','Pernikahan & acara','Rombongan','Lainnya'],hours:'Setiap hari, 08.00–21.00 WIB',sub:'Beri tahu tanggal dan jumlah tamu; konsierge kami membalas dalam beberapa jam.'},
 cta:{title:'Siap menghabiskan beberapa malam yang tenang?',text:'Pesan langsung untuk mendapat sarapan dan transfer speedboat tanpa biaya.',btn:'Hubungi reservasi'}
};
