/* Data situs VOLT X1 (fiktif) — SUV listrik. */
export default {
 id:'volt',type:'shop',frames:7,
 fonts:'https://fonts.googleapis.com/css2?family=Sora:wght@500;700;800&family=Inter:wght@400;500;600&display=swap',
 theme:{mode:'dark',bg:'#0a0b0d',bg2:'#111317',ink:'#f1f2f4',mut:'#9aa0aa',acc:'#e8ff3a',accInk:'#141800',line:'#23262c',card:'#14161a',fh:"'Sora',system-ui,sans-serif",fb:"Inter,system-ui,sans-serif",radius:'8px'},
 brand:{name:'VOLT',mark:'V',tagline:'SUV listrik keluarga dengan jarak tempuh 620 km dan ruang yang tidak berkompromi.',email:'drive@volt.example',phone:'(021) 555-0100',address:'VOLT Center, Jl. TB Simatupang 1, Jakarta Selatan'},
 promo:'Booking fee Rp 5 juta, dapat dikembalikan penuh · Wallbox gratis untuk 500 pemesan pertama',
 home:{eyebrow:'SUV listrik · Pre-order dibuka',title:'Bergerak <em>tanpa suara</em>, tiba tanpa kompromi.',sub:'VOLT X1: 620 km sekali isi daya, 0–100 km/jam 4,9 detik, lima kursi dewasa, dan bagasi 640 liter.',cta:'Konfigurasi VOLT X1',heroImg:3,storyImg:4,storyTag:'Desain',storyTitle:'Garis bersih yang dibentuk angin.',story:'Koefisien drag 0,24 dan lampu depan setipis garis. Masuk ke showroom 3D: ganti cat, ganti velg, nyalakan lampu, dan lihat mobil berputar di atas piringan.'},
 usp:[['Jarak 620 km','Siklus WLTP'],['Pengisian cepat','10–80% dalam 22 menit'],['Garansi baterai','8 tahun / 160.000 km'],['Test drive','Datang ke rumah Anda']],
 categories:[{id:'mobil',name:'Mobil',desc:'VOLT X1 — pesan sekarang',img:3,pos:'50% 60%'},{id:'pengisian',name:'Pengisian',desc:'Wallbox & kabel',img:5,pos:'50% 50%'},{id:'aksesori',name:'Aksesori',desc:'Velg, pelindung, perlengkapan',img:4,pos:'50% 50%'}],
 products:[
  {id:'volt-x1',cat:'mobil',name:'VOLT X1',short:'SUV listrik 5 kursi, AWD 420 PK, 620 km.',price:689000000,badge:'Pre-order',feat:1,img:3,pos:'50% 60%',rating:4.9,reviews:312,kw:['volt x1','volt'],variants:[{key:'Warna',label:'Warna cat',values:[{v:'Merah Api',sw:'#c4102c'},{v:'Putih Mutiara',sw:'#f3f4f6',hue:0},{v:'Biru Malam',sw:'#0a1c4a',hue:200},{v:'Hijau Hutan',sw:'#0d3a2b',hue:100},{v:'Abu Titanium',sw:'#8a9096',hue:0}]},{key:'Velg',label:'Velg',values:[{v:'Aero 20"'},{v:'Sport 21"',delta:14000000}]},{key:'Baterai',label:'Baterai',values:[{v:'Standar 82 kWh'},{v:'Long Range 100 kWh',delta:68000000}]}],desc:'SUV listrik dengan platform 800 volt, suspensi udara adaptif, dan atap panoramik. Harga on the road Jakarta; booking fee dapat dikembalikan.',spec:[['Daya','420 PK, AWD'],['0–100 km/jam','4,9 detik'],['Jarak tempuh','620 km WLTP'],['Pengisian cepat','10–80% dalam 22 mnt'],['Bagasi','640 L + 90 L depan']]},
  {id:'wallbox',cat:'pengisian',name:'Wallbox Rumah 11 kW',short:'Pengisi dinding pintar dengan penjadwalan lewat aplikasi.',price:18500000,feat:1,img:5,pos:'50% 50%',rating:4.7,reviews:84,kw:['wallbox'],variants:[{key:'Pemasangan',label:'Pemasangan',values:[{v:'Tanpa pemasangan'},{v:'Dengan pemasangan',delta:4500000}]}],desc:'Mengisi VOLT X1 penuh semalam. Dilengkapi proteksi arus bocor dan penjadwalan tarif malam.',spec:[['Daya','11 kW, 3 fase'],['Kabel','5 m Type 2'],['Konektivitas','Wi-Fi']]},
  {id:'kabel-portabel',cat:'pengisian',name:'Kabel Pengisi Portabel',short:'Kabel dengan adaptor untuk stopkontak rumah.',price:6900000,img:4,pos:'50% 70%',rating:4.5,reviews:36,kw:['kabel'],desc:'Untuk pengisian darurat 2,3 kW di mana saja ada listrik.',spec:[['Daya','2,3 kW'],['Panjang','6 m']]},
  {id:'velg-sport',cat:'aksesori',name:'Velg Sport 21" (set 4)',short:'Velg tempa ringan, finishing hitam doff.',price:42000000,img:2,pos:'30% 70%',rating:4.8,reviews:22,kw:['velg'],desc:'Mengurangi bobot tak terpegas 11 kg dan menambah ketajaman kemudi.',spec:[['Bahan','Aluminium tempa'],['Ukuran','21 × 9,5']]},
  {id:'ppf',cat:'aksesori',name:'Pelindung Cat PPF Full Body',short:'Lapisan transparan anti gores dengan garansi 10 tahun.',price:38000000,img:6,pos:'60% 50%',rating:4.7,reviews:41,kw:['ppf'],desc:'Dipasang di pusat layanan VOLT, menjaga cat dari goresan dan batu kerikil.',spec:[['Garansi','10 tahun'],['Waktu pasang','3 hari']]}],
 coupons:{VOLTLOYAL:{type:'fixed',value:5000000,min:100000000},WALLBOX5:{type:'percent',value:5,max:1000000}},freeShip:0,
 shipping:[{id:'reg',name:'Antar ke alamat / dealer',eta:'Mobil: 8–12 minggu · Aksesori: 3–5 hari',price:0},{id:'pick',name:'Ambil di VOLT Center',eta:'Sesuai jadwal',price:0}],
 payments:[{id:'va',name:'Virtual account bank',note:'Booking fee & aksesori'},{id:'card',name:'Kartu kredit',note:'Cicilan 0% untuk aksesori'},{id:'fin',name:'Pembiayaan mobil',note:'Simulasi — tim kami menghubungi Anda'}],
 shipNote:'Mobil diserahkan di VOLT Center atau alamat Anda dengan penyerahan resmi. Booking fee dapat dikembalikan penuh sebelum produksi dimulai. Aksesori: retur 14 hari.',
 testi:[['Mengemudinya hening dan responsif. Anak-anak suka atap panoramiknya.','Reza P.','Jakarta'],['Pengisian cepatnya benar-benar 22 menit di perjalanan Bandung.','Karina O.','Bandung'],['Layanan test drive ke rumah sangat praktis.','Ivan Z.','Tangerang']],
 about:{title:'Cerita VOLT',sub:'Kendaraan listrik untuk keluarga yang ingin perjalanan jauh tanpa cemas.',img:3,paras:['VOLT didirikan pada 2021 oleh insinyur otomotif yang ingin menunjukkan bahwa mobil listrik bisa praktis, indah, dan terjangkau untuk jarak jauh.','Kami merancang platform 800 volt dan jaringan pengisian mitra di jalur utama Jawa dan Sumatra.','Layanan kami dimulai dari test drive di rumah hingga perawatan berkala di pusat layanan.'],values:[['Praktis dulu','Ruang, jarak, dan kemudahan di depan.'],['Transparan','Harga on the road dan biaya pengisian jelas.'],['Bertanggung jawab','Baterai dapat didaur ulang.']]},
 faq:[['Apakah booking fee dapat dikembalikan?','Ya, penuh sebelum produksi dimulai.'],['Berapa lama pengisian di rumah?','Dengan wallbox 11 kW, penuh dalam ±9 jam.'],['Apakah ada garansi baterai?','8 tahun atau 160.000 km.'],['Bisakah test drive di rumah?','Bisa di Jabodetabek, jadwalkan lewat halaman kontak.']],
 contact:{img:2,topics:['Test drive','Pesanan saya','Pembiayaan','Lainnya'],hours:'Setiap hari, 10.00–20.00 WIB'}
};
