/* Panel company profile untuk situs 3D: tentang, layanan, proyek/studi kasus, wawasan, karier, kontak, dan reservasi.
   Data dari js/sites/<id>.js (fiktif). Formulir disimpan di peramban (simulasi; ganti `api` di js/site/store.js untuk backend). */
import {esc,$,$$,validate,fmtDate,toast} from '../site/ui.js';
import {api} from '../site/store.js';
export {contact} from './shop.js';

const btn=(h,t,g)=>'<a class="wbtn'+(g?' ghost':'')+'" href="#'+h+'">'+t+'</a>';
export function about(s,where){const a=s.about;return{title:'Tentang',html:'<p class="wk">'+esc(where||'Tentang')+'</p><h1 class="wh">'+esc(a.title)+'</h1><p class="wl">'+esc(a.sub)+'</p>'+a.paras.map(p=>'<p>'+esc(p)+'</p>').join('')
  +'<h3>Nilai kerja</h3>'+a.values.map(v=>'<p><b>'+esc(v[0])+'.</b> '+esc(v[1])+'</p>').join('')
  +(a.timeline?'<h3>Perjalanan</h3><ol class="wtl">'+a.timeline.map(t=>'<li class="done"><b>'+t[0]+'</b><small>'+esc(t[1])+'</small></li>').join('')+'</ol>':'')
  +(a.team?'<h3>Tim pimpinan</h3><div class="wteam">'+a.team.map(t=>'<div><span>'+t[0].replace(/^(dr\.|Dr\.|Prof\.|Ibu|Pak|Kak|Chef)\s+/,'').split(' ').map(w=>w[0]).slice(0,2).join('')+'</span><b>'+esc(t[0])+'</b><small>'+esc(t[1])+'</small></div>').join('')+'</div>':'')}}
export function stats(s){return '<div class="wstat">'+s.home.stats.map(x=>'<div><b>'+esc(x[0])+esc(x[1])+'</b><span>'+esc(x[2])+'</span></div>').join('')+'</div>'}
export function services(s,where){return{title:s.svcTitle||'Layanan',html:'<p class="wk">'+esc(where||'Layanan')+'</p><h1 class="wh">'+esc(s.svcTitle||'Layanan')+'</h1><p class="wl">'+esc(s.svcSub||'')+'</p>'
  +'<div class="wlist">'+s.services.map((x,i)=>'<a class="wli2 rv" href="#/layanan/'+x.id+'"><em>0'+(i+1)+'</em><span><b>'+esc(x.name)+'</b><small>'+esc(x.short)+'</small></span><i>→</i></a>').join('')+'</div>'}}
export function service(s,id,extra){const k=s.services.findIndex(v=>v.id===id);if(k<0)return null;const x=s.services[k],nx=s.services[(k+1)%s.services.length];
  return{title:x.name,html:'<p class="wk"><a href="#/layanan">← '+esc(s.svcTitle||'Layanan')+'</a></p><h1 class="wh">'+esc(x.name)+'</h1><p class="wl">'+esc(x.short)+'</p>'+(extra||'')+'<p>'+esc(x.desc)+'</p><ul class="wticks">'+x.points.map(p=>'<li>'+esc(p)+'</li>').join('')+'</ul>'
  +'<h3>Cara kerja</h3><ol class="wsteps">'+x.steps.map(t=>'<li><b>'+esc(t[0])+'</b>'+esc(t[1])+'</li>').join('')+'</ol><div class="wrow">'+btn('/kontak',esc(s.cta.btn))+btn('/layanan/'+nx.id,'Berikutnya: '+esc(nx.name),1)+'</div>'}}
export function projects(s,r,where){const f=r.q.get('s')||'semua',secs=['semua'].concat([...new Set(s.projects.map(p=>p.sector))]);
  return{title:s.projLabel||'Proyek',html:'<p class="wk">'+esc(where||s.projLabel||'Proyek')+'</p><h1 class="wh">'+esc(s.projTitle||'Proyek')+'</h1><p class="wl">'+esc(s.projSub||'')+'</p>'
  +'<div class="wchips">'+secs.map(c=>'<a class="wchip'+(c===f?' on':'')+'" href="#/proyek'+(c==='semua'?'':'?s='+encodeURIComponent(c))+'">'+(c==='semua'?'Semua':esc(c))+'</a>').join('')+'</div>'
  +'<div class="wlist">'+s.projects.filter(p=>f==='semua'||p.sector===f).map(x=>'<a class="wli2 rv" href="#/proyek/'+x.id+'"><em>'+x.year+'</em><span><b>'+esc(x.name)+'</b><small>'+esc(x.client)+' · '+esc(x.sector)+'</small></span><i>→</i></a>').join('')+'</div>'}}
export function project(s,id,extra){const k=s.projects.findIndex(v=>v.id===id);if(k<0)return null;const x=s.projects[k],nx=s.projects[(k+1)%s.projects.length];
  return{title:x.name,html:'<p class="wk"><a href="#/proyek">← '+esc(s.projLabel||'Proyek')+'</a> · '+esc(x.sector)+' · '+x.year+'</p><h1 class="wh">'+esc(x.name)+'</h1><p class="wl">'+esc(x.summary)+'</p>'+(extra||'')
  +'<dl class="wsum"><div><dt>'+(s.projClientLabel||'Klien')+'</dt><dd>'+esc(x.client)+'</dd></div></dl><h3>'+(s.projLabels?s.projLabels[0]:'Tantangan')+'</h3><p>'+esc(x.challenge)+'</p><h3>'+(s.projLabels?s.projLabels[1]:'Solusi')+'</h3><p>'+esc(x.solution)+'</p>'
  +'<div class="wstat">'+x.results.map(v=>'<div><b>'+esc(v[0])+'</b><span>'+esc(v[1])+'</span></div>').join('')+'</div><p class="wtiny">'+esc(s.projNote||'Angka dan klien pada studi kasus ini fiktif.')+'</p>'
  +'<div class="wrow">'+(s.projCta?btn(s.projCta[0].replace('{id}',x.id),s.projCta[1]):btn('/kontak','Diskusikan proyek Anda'))+btn('/proyek/'+nx.id,'Berikutnya →',1)+'</div>'}}
export function insights(s,where){return{title:'Wawasan',html:'<p class="wk">'+esc(where||'Wawasan')+'</p><h1 class="wh">Wawasan</h1><p class="wl">Catatan dan pandangan dari tim kami.</p>'
  +'<div class="wlist">'+s.insights.map(x=>'<a class="wli2 rv" href="#/wawasan/'+x.id+'"><em>'+esc(x.tag)+'</em><span><b>'+esc(x.title)+'</b><small>'+fmtDate(x.date)+' · '+esc(x.excerpt)+'</small></span><i>→</i></a>').join('')+'</div>'}}
export function insight(s,id){const x=s.insights.find(v=>v.id===id);if(!x)return null;
  return{title:x.title,html:'<p class="wk"><a href="#/wawasan">← Wawasan</a> · '+esc(x.tag)+' · '+fmtDate(x.date)+'</p><h1 class="wh">'+esc(x.title)+'</h1><p class="wl">'+esc(x.excerpt)+'</p>'+x.body.map(p=>'<p>'+esc(p)+'</p>').join('')+'<div class="wrow">'+btn('/kontak',esc(s.cta.btn))+'</div>'}}
export function careers(s,where){return{title:'Karier',html:'<p class="wk">'+esc(where||'Karier')+'</p><h1 class="wh">Karier</h1><p class="wl">Bergabung dengan tim '+esc(s.brand.name)+'.</p>'
  +s.jobs.map(j=>'<details><summary>'+esc(j.title)+' <small>'+esc(j.place)+' · '+esc(j.type)+'</small></summary><p>'+esc(j.desc)+'</p><ul class="wticks">'+j.req.map(q=>'<li>'+esc(q)+'</li>').join('')+'</ul><a class="wbtn sm" href="#/kontak?topik='+encodeURIComponent('Karier: '+j.title)+'">Lamar posisi ini</a></details>').join('')
  +'<p class="wtiny">Tidak ada yang cocok? Kirim profil Anda lewat halaman kontak.</p>'}}

/* reservasi / janji temu: o = {title, where, kind:'kamar'|'konsultasi', options:[{id,name,price,note}], optLabel, dates:true, guests, slots} */
export function booking(s,W,o,r){const pre=r&&r.q.get('pilih');const today=new Date(Date.now()+864e5).toISOString().slice(0,10);
  return{title:o.title,html:'<p class="wk">'+esc(o.where)+'</p><h1 class="wh">'+esc(o.title)+'</h1><p class="wl">'+esc(o.sub||'')+'</p><form class="wform" id="bkF" novalidate>'
  +'<h3>1 · '+esc(o.optLabel)+'</h3>'+o.options.map((x,i)=>'<label class="wopt"><input type="radio" name="opsi" value="'+x.id+'"'+((pre?pre===x.id:i===0)?' checked':'')+'><span><b>'+esc(x.name)+'</b><em>'+esc(x.note||'')+'</em></span><i>'+esc(x.priceLabel||'')+'</i></label>').join('')
  +'<h3>2 · Waktu</h3>'+(o.nights?'<div class="w2"><div class="fld"><label for="bIn">Check-in</label><input id="bIn" name="masuk" type="date" required min="'+today+'" value="'+today+'"></div><div class="fld"><label for="bOut">Malam</label><select id="bOut" name="malam">'+[1,2,3,4,5,6,7].map(n=>'<option'+(n===2?' selected':'')+'>'+n+'</option>').join('')+'</select></div></div><div class="fld"><label for="bG">Tamu</label><select id="bG" name="tamu">'+[1,2,3,4].map(n=>'<option'+(n===2?' selected':'')+'>'+n+' orang</option>').join('')+'</select></div>'
    :'<div class="w2"><div class="fld"><label for="bIn">Tanggal</label><input id="bIn" name="tanggal" type="date" required min="'+today+'" value="'+today+'"></div><div class="fld"><label for="bSl">Jam</label><select id="bSl" name="jam">'+o.slots.map(x=>'<option>'+x+'</option>').join('')+'</select></div></div><div class="fld"><label for="bM">Cara</label><select id="bM" name="cara"><option>Daring (video)</option><option>Tatap muka di klinik</option></select></div>')
  +'<h3>3 · Data Anda</h3><div class="fld"><label for="bn">Nama lengkap</label><input id="bn" name="nama" required autocomplete="name"></div><div class="fld"><label for="be">Email</label><input id="be" name="email" type="email" required autocomplete="email"></div><div class="fld"><label for="bp">Ponsel</label><input id="bp" name="telp" required data-phone inputmode="tel" autocomplete="tel"></div>'
  +'<div class="fld"><label for="bc">Catatan (opsional)</label><textarea id="bc" name="catatan" rows="2"></textarea></div><div id="bkSum"></div><button class="wbtn full" id="bkGo">'+esc(o.cta||'Kirim')+'</button><p class="wtiny">Simulasi: tidak ada pemesanan atau pembayaran sungguhan. Data hanya tersimpan di peramban ini.</p></form>',
  after:root=>{const f=$('#bkF',root);const draw=()=>{const x=o.options.find(v=>v.id===f.opsi.value);W.onBookingChange&&W.onBookingChange(x);if(o.nights&&x.price){const n=+f.malam.value;$('#bkSum').innerHTML='<dl class="wsum"><div><dt>'+esc(x.name)+' × '+n+' malam</dt><dd>Rp '+(x.price*n).toLocaleString('id-ID')+'</dd></div><div class="tt"><dt>Total</dt><dd>Rp '+(x.price*n).toLocaleString('id-ID')+'</dd></div></dl>'}};f.addEventListener('change',draw);draw();
    f.onsubmit=async e=>{e.preventDefault();if(!validate(f))return;const b=$('#bkGo');b.disabled=true;b.textContent='Memproses…';const d=Object.fromEntries(new FormData(f));const x=o.options.find(v=>v.id===d.opsi);
      const res=await api.submitContact(s.id,Object.assign({jenis:o.kind,opsi:x.name},d));W.sfx('chime');W.kick(1.2);
      f.outerHTML='<div class="wdone"><b>'+esc(o.doneTitle||'Terkirim')+'</b><p>Kode '+(o.kind==='kamar'?'reservasi':'janji')+' <b>'+res.id.replace('MSG',o.kind==='kamar'?'RSV':'APT')+'</b> untuk '+esc(x.name)+(d.masuk?', check-in '+fmtDate(d.masuk)+', '+esc(d.malam)+' malam':d.tanggal?', '+fmtDate(d.tanggal)+' pukul '+esc(d.jam):'')+'. Konfirmasi dikirim ke '+esc(d.email)+'.</p></div>'}}}}
